version: "3.4"

services:
  mysql_db:
    image: mysql:8
    environment:
      - MYSQL_ROOT_PASSWORD=123456
      - MYSQL_DATABASE=bank
      - MYSQL_USER=user
      - MYSQL_PASSWORD=123456
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - 3306:3306

volumes:
  mysql_data:
    driver: local
